/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package kuat.cli;

import picocli.CommandLine;
import picocli.CommandLine.Command;

import java.util.concurrent.Callable;

@Command(name = "kuat")
public class Main implements Callable<Integer> {
	@Override
	public Integer call() {
		return null;
	}

	public static int run(String[] args) {
		return new CommandLine(new Main()).execute(args);
	}

	public static void main(String[] args) {
		System.exit(run(args));
	}
}
