/*
 * This file was generated by the Gradle 'init' task.
 *
 * The settings file is used to specify which projects to include in your build.
 */

pluginManagement {
	// Include 'plugins build' to define convention plugins.
	includeBuild("build-logic")
}

plugins {
	// Apply the foojay-resolver plugin to allow automatic download of JDKs
	id("org.gradle.toolchains.foojay-resolver-convention") version "0.7.0"
}


rootProject.name = "kuat"

enableFeaturePreview("TYPESAFE_PROJECT_ACCESSORS")

include("cli")
include("core")
include("plugin-java")
